name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # o la rama que desees

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # Versión de .NET Core que deseas utilizar

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and test
      run: dotnet build --configuration Release
